// config/index.tsx
import { cookieStorage, createStorage } from "wagmi";
import { WagmiAdapter } from "@reown/appkit-adapter-wagmi";
import { base, baseSepolia } from "@reown/appkit/networks";
import type { Chain } from "viem";

// Read Project ID from environment variables
export const projectId = import.meta.env.VITE_PROJECT_ID || "";

// Ensure Project ID is defined at build time
if (!projectId) {
  throw new Error(
    "VITE_PROJECT_ID is not defined. Please set it in .env.local",
  );
}

// Define supported networks (Base for production, Base Sepolia for development)
const isProd = import.meta.env.PROD;
export const networks: [Chain, ...Chain[]] = [isProd ? base : baseSepolia];
export const networkIds = networks.map(network => network.id);

// Create the Wagmi adapter instance
export const wagmiAdapter = new WagmiAdapter({
  storage: createStorage({ storage: cookieStorage }),
  ssr: true,
  projectId,
  networks,
});

// Export the Wagmi config generated by the adapter
export const config = wagmiAdapter.wagmiConfig;
